trigger:
  branches:
    include:
    - master
    - releases/*
  paths:
    include:
    - azure-pipelines.yml
pool:
  vmImage: ubuntu-latest
variables:
  tag: sdk:5.0.100
steps:
- task: Docker@2
  inputs:
    containerRegistry: tencentyun
    command: login
- task: PowerShell@2
  inputs:
    targetType: inline
    script: "$env:version=\"$(tag)\"\n\ndocker pull mcr.microsoft.com/dotnet/$env:version\n\ndocker tag mcr.microsoft.com/dotnet/$env:version ccr.ccs.tencentyun.com/dotnet-core/$env:version\ndocker push ccr.ccs.tencentyun.com/dotnet-core/$env:version\0"
- task: wangshuai.Message.send-message-task.SendToftqq@1
  displayName: 发送到方糖
  inputs:
    ftqqConnection: ftqqConnection
    text: pipline retag sucess
    desp: $(tag)
